export const BASE_APIURL = 'http://35.160.197.175:3006'

export const SIGN_IN_APIURL = BASE_APIURL + '/api/v1/user/login'
export const ADDTO_FAVOURITE_APIURL = BASE_APIURL + '/api/v1/recipe/add-to-cooking-list'
export const REMOVEFROM_FAVOURITE_APIURL = BASE_APIURL + '/api/v1/recipe/rm-from-cooking-list'
export const GETFAVOURITE_APIURL = BASE_APIURL + '/api/v1/recipe/cooking-list'
export const DELETE_APIURL = BASE_APIURL + '/api/v1/recipe/'
export const FEED_APIURL = BASE_APIURL + '/api/v1/recipe/feeds'
export const SEARCH_FEED_APIURL = BASE_APIURL + '/api/v1/recipe/feeds?q='
export const ADD_RECIPE_APIURL = BASE_APIURL + '/api/v1/recipe/add'
export const ADD_INGREDIENT_APIURL = BASE_APIURL + '/api/v1/recipe/add-ingredient'
export const ADD_INSTRUCTION_APIURL = BASE_APIURL + '/api/v1/recipe/add-instruction'
export const UPDATE_RECIPE_IMAGE_APIURL = BASE_APIURL + '/api/v1/recipe/add-update-recipe-photo'
export const COMMON_APIURL = BASE_APIURL + '/api/v1/recipe/'

export const POST_METHOD = 'POST'
export const GET_METHOD = 'GET'
export const PUT_METHOD = 'PUT'
export const DELETE_METHOD = 'DELETE'
export const CONTENT_TYPE_VALUE = 'application/json'